In [1]:
from pureml_evaluate.metrics.model.pairwise_distances_chunked.pairwise_distances_chunked import PairwiseDistancesChunked

In [2]:
pd = PairwiseDistancesChunked()

In [3]:
import numpy as np


X = np.random.RandomState(0).rand(5, 3)



In [4]:
pd.compute(X)

{'pairwise_distances_chunked': <generator object pairwise_distances_chunked at 0x7f53c78b2030>}

In [5]:
result = pd.compute(X)

In [6]:
result['pairwise_distances_chunked']

<generator object pairwise_distances_chunked at 0x7f53c78b20a0>

In [7]:
D_chunk = next(result['pairwise_distances_chunked'])

In [8]:
D_chunk

array([[0.        , 0.29473397, 0.41689499, 0.19662693, 0.57216693],
       [0.29473397, 0.        , 0.57586803, 0.41860234, 0.76350759],
       [0.41689499, 0.57586803, 0.        , 0.44940452, 0.90274337],
       [0.19662693, 0.41860234, 0.44940452, 0.        , 0.51150232],
       [0.57216693, 0.76350759, 0.90274337, 0.51150232, 0.        ]])

In [9]:
r = .2
def reduce_func(D_chunk, start):
    neigh = [np.flatnonzero(d < r) for d in D_chunk]
    avg_dist = (D_chunk * (D_chunk < r)).mean(axis=1)
    return neigh, avg_dist
gen = pd.compute(X, reduce_func=reduce_func)
neigh, avg_dist = next(gen['pairwise_distances_chunked'])
neigh

avg_dist


array([0.03932539, 0.        , 0.        , 0.03932539, 0.        ])

In [10]:
neigh

[array([0, 3]), array([1]), array([2]), array([0, 3]), array([4])]

In [11]:
avg_dist

array([0.03932539, 0.        , 0.        , 0.03932539, 0.        ])

In [12]:
r = [.2, .4, .4, .3, .1]
def reduce_func(D_chunk, start):
    neigh = [np.flatnonzero(d < r[i])
             for i, d in enumerate(D_chunk, start)]
    return neigh

result = pd.compute(X,reduce_func=reduce_func)
neigh  = next(result['pairwise_distances_chunked'])


In [13]:
neigh

[array([0, 3]), array([0, 1]), array([2]), array([0, 3]), array([4])]